version: '3.9'

services:
  nginx:
    build:  ./nginx
    image: cbrwrapper-nginx
    ports:
      - 1488:80

  backend:
    build: .
    image: cbrwrapper-backend

  frontend:
    image: cbrwrapper-frontend
